name: iac-scan

on:
  workflow_dispatch:

jobs:

  SCA:
 
    runs-on: ubuntu-latest

    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~

      - name: Dumping Source Code
        uses: actions/checkout@v3

#~~~~~~~~~~ Running Dependency Scan ~~~~~~~~~~
        
      - name: Dependency Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#~~~~~~~~~~ Uploading Results ~~~~~~~~~~

      - name: Uploading Scan Reports 
        uses: actions/upload-artifact@v1
        with:
          name: Dependency-and-Secret-Reports
          path: reports


  IAC_Scan:
  
    runs-on: ubuntu-latest
    
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
